# Generated by Django 5.0 on 2025-12-26 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('HR', 'HR'), ('CLIENT', 'Client'), ('PEER', 'Peer')], max_length=10)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='SharedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('last_message_count', models.IntegerField(default=0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.simulation')),
            ],
        ),
    ]
