# Generated by Django 5.0 on 2025-12-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires_submission',
            field=models.BooleanField(default=False),
        ),
    ]
