# Generated by Django 5.0 on 2025-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_task_requires_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='client_name',
            field=models.CharField(default='Client', max_length=100),
        ),
        migrations.AddField(
            model_name='simulation',
            name='hr_name',
            field=models.CharField(default='HR Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='simulation',
            name='peer_name',
            field=models.CharField(default='Team Peer', max_length=100),
        ),
    ]
