# Generated by Django 5.0 on 2025-12-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_simulation_client_name_simulation_hr_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=0, help_text='Score from 0-100'),
        ),
    ]
