# Generated by Django 5.0 on 2025-12-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_task_feedback_task_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='final_report_data',
            field=models.JSONField(blank=True, help_text='Stored AI report', null=True),
        ),
    ]
