# Generated by Django 5.0 on 2026-01-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_simulation_final_report_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
