# Generated by Django 6.0.2 on 2026-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0006_task_attempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="expected_output_template",
            field=models.TextField(
                blank=True, default="", help_text="Generated by Thinker AI"
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="project_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
