from django.db import models
from django.contrib.auth.models import User



class Simulation(models.Model):
    STATUS_CHOICES = [('ongoing', 'Ongoing'), ('paused', 'Paused'), ('completed', 'Completed')]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role_title = models.CharField(max_length=100)
    project_title = models.CharField(max_length=200, default='', blank=True)
    description = models.TextField(default='', blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='ongoing')
    created_at = models.DateTimeField(auto_now_add=True)
    hr_name = models.CharField(max_length=100, default="HR Manager")
    peer_name = models.CharField(max_length=100, default="Team Peer")
    client_name = models.CharField(max_length=100, default="Client")
    final_report_data = models.JSONField(null=True, blank=True, help_text="Stored AI report")
    expected_output_template = models.TextField(default='', blank=True, help_text="Generated by Thinker AI")

    @property
    def progress_percentage(self):
        total_tasks = self.tasks.count()
        if total_tasks == 0:
            return 0
        completed_tasks = self.tasks.filter(is_completed=True).count()
        return int((completed_tasks / total_tasks) * 100)


class Task(models.Model):
    simulation = models.ForeignKey(Simulation, related_name='tasks', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    instruction = models.TextField()
    difficulty = models.IntegerField(default=1)
    is_completed = models.BooleanField(default=False)
    is_skipped = models.BooleanField(default=False)
    order = models.PositiveIntegerField()
    requires_submission = models.BooleanField(default=False)
    attempts = models.IntegerField(default=0)
    score = models.IntegerField(default=0, help_text="Score from 0-100")
    feedback = models.TextField(blank=True, null=True)
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_photo = models.ImageField(upload_to='profile_photos/', default='profile_photos/default.png', blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"
        